export enum AvailabilityStatus {
  SEMPRE_DISPONIVEL = 'SEMPRE_DISPONIVEL',
  HORARIO_ESPECIFICO = 'HORARIO_ESPECIFICO',
  DIAS_ESPECIFICOS = 'DIAS_ESPECIFICOS',
  SAZONAL = 'SAZONAL',
  TEMPORARIAMENTE_INDISPONIVEL = 'TEMPORARIAMENTE_INDISPONIVEL',
}
