export enum StockStatus {
  DISPONIVEL = 'DISPONIVEL',
  INDISPONIVEL = 'INDISPONIVEL',
  ESTOQUE_BAIXO = 'ESTOQUE_BAIXO',
  ESGOTADO = 'ESGOTADO',
  VENCIDO = 'VENCIDO',
  RESERVADO = 'RESERVADO',
}
