# Docker Compose para desenvolvimento (apenas serviços)

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: pdv-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - pdv-dev-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: pdv-redis-dev
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - pdv-dev-network

  # RabbitMQ Message Broker
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: pdv-rabbitmq-dev
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
    ports:
      - "${RABBITMQ_PORT}:5672" # AMQP port
      - "${RABBITMQ_MGMT_PORT}:15672" # Management UI
    volumes:
      - rabbitmq_dev_data:/var/lib/rabbitmq
    networks:
      - pdv-dev-network

volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local
  rabbitmq_dev_data:
    driver: local

networks:
  pdv-dev-network:
    driver: bridge
